## Data Science Portfolio - Page Visits Funnel Notebook ##

### Created by: Albert Schultz ###

### Date Created: 05/30/2023 ###

### Version: 1.00 ###

### Executive Summary ###
This notebook contains the Page Visigs Funnel Portfolio Python Pandas project.

## Table of Contents ##

1. [Introduction](#1.-Introduction)
2. [Understanding Purpose, Goals, and Vision](#2.-Understanding-Purpose,-Goals,-and-Vision)
3. [Import the Raw Datasets](#3.-Import-the-Raw-Datasets)
4. [Perform Merges of DataFrames](#4.-Perform-Merges-of-DataFrames)
5. [Perform EDA on the All Data Frame](#5.-Perform-EDA-on-the-All-Data-Frame)
6. [Summary](#Summary)

## 1. Introduction ##

In this project, the notebook puts together a Page Visits Funneling script and table that contains analysis on visits to the Cool T-Shirts Inc (fiction business) using the **visits.csv, cart.csv, checkout.csv, and purchase.csv** files for the analysis.

**Initialize the Notebook for data access, import library modules, and set the working directory for this project.**

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

## 2. Understanding Purpose, Goals, and Vision ##

The vision of this Page Visits Funnling Notebook is to understand the process of performing merges, calculations, and analysis of the page visits for the fiction company, Cool T-Shirts Inc.

**Vision:** TO showcase the analyzed table of the numbers of visits to the Cool T-Shirt Inc. store with various angle of their datasets in dataframes so stakeholders can udnerstand traffic visits more efficiently.

**Goals:**
1. Review the Cool T-shirts' attributes for data inconsistencies and import it into this notebook Python IDE as labeled dataframes. 
2. Perform data cleaning, extractions, merging of tables from separate data frames. 
3. Analyzed the clean dataframes to find out the page visits on certain times of days to various types of visits from various sources. 
5. Present the cleaned data frame in a single dataframe.

## 3. Import the Raw Datasets ##

**Introduction:** This section contains the code to import Cool T-Shirt's dataset in a form of csv and convert them into dataframe variables.

1. Import the datasets and relabled as new dataframes; **visits, cart, checkout, and purchase**.

In [7]:
visits = pd.read_csv('/kaggle/input/page-funnel-dataset/visits.csv', parse_dates=[1])
cart = pd.read_csv('/kaggle/input/page-funnel-dataset/cart.csv', parse_dates=[1])
checkout = pd.read_csv('/kaggle/input/page-funnel-dataset/checkout.csv', parse_dates=[1])
purchase = pd.read_csv('/kaggle/input/page-funnel-dataset/purchase.csv', parse_dates=[1])

2. View the first five rows of all of the four data frames for data inconsistencies.

In [9]:
print(visits.head(5))
print(cart.head(5))
print(checkout.head(5))
print(purchase.head(5))

                                user_id          visit_time
0  943647ef-3682-4750-a2e1-918ba6f16188 2017-04-07 15:14:00
1  0c3a3dd0-fb64-4eac-bf84-ba069ce409f2 2017-01-26 14:24:00
2  6e0b2d60-4027-4d9a-babd-0e7d40859fb1 2017-08-20 08:23:00
3  6879527e-c5a6-4d14-b2da-50b85212b0ab 2017-11-04 18:15:00
4  a84327ff-5daa-4ba1-b789-d5b4caf81e96 2017-02-27 11:25:00
                                user_id           cart_time
0  2be90e7c-9cca-44e0-bcc5-124b945ff168 2017-11-07 20:45:00
1  4397f73f-1da3-4ab3-91af-762792e25973 2017-05-27 01:35:00
2  a9db3d4b-0a0a-4398-a55a-ebb2c7adf663 2017-03-04 10:38:00
3  b594862a-36c5-47d5-b818-6e9512b939b3 2017-09-27 08:22:00
4  a68a16e2-94f0-4ce8-8ce3-784af0bbb974 2017-07-26 15:48:00
                                user_id       checkout_time
0  d33bdc47-4afa-45bc-b4e4-dbe948e34c0d 2017-06-25 09:29:00
1  4ac186f0-9954-4fea-8a27-c081e428e34e 2017-04-07 20:11:00
2  3c9c78a7-124a-4b77-8d2e-e1926e011e7d 2017-07-13 11:38:00
3  89fe330a-8966-4756-8f7c-3bdbcd47279a 2017-04-20 16:15:00
4  3ccdaf69-2d30-40de-b083-51372881aedd 2017-01-08 20:52:00
                                user_id       purchase_time
0  4b44ace4-2721-47a0-b24b-15fbfa2abf85 2017-05-11 04:25:00
1  02e684ae-a448-408f-a9ff-dcb4a5c99aac 2017-09-05 08:45:00
2  4b4bc391-749e-4b90-ab8f-4f6e3c84d6dc 2017-11-20 20:49:00
3  a5dbb25f-3c36-4103-9030-9f7c6241cd8d 2017-01-22 15:18:00
4  46a3186d-7f5a-4ab9-87af-84d05bfd4867 2017-06-11 11:32:00

## 4. Perform Merges of DataFrames ##

**Introduction:** In this section, I will be performing several merges to single DataFrames to make the data more tidy.

1. Combine **visits** and **cart** using the **left merge** method and show how many observations after merging visits and cart.

In [15]:
pd.merge(visits, cart, how = 'left').user_id.count()

2000

2. Show the first 10 rows of the merged visits and cart.

In [16]:
pd.merge(visits, cart, how = 'left').head(10)

,user_id,visit_time,cart_time
0,943647ef-3682-4750-a2e1-918ba6f16188,2017-04-07 15:14:00,NaT
1,0c3a3dd0-fb64-4eac-bf84-ba069ce409f2,2017-01-26 14:24:00,2017-01-26 14:44:00
2,6e0b2d60-4027-4d9a-babd-0e7d40859fb1,2017-08-20 08:23:00,2017-08-20 08:31:00
3,6879527e-c5a6-4d14-b2da-50b85212b0ab,2017-11-04 18:15:00,NaT
4,a84327ff-5daa-4ba1-b789-d5b4caf81e96,2017-02-27 11:25:00,NaT
5,7bc62113-d51d-4e6b-85e0-1cf29e3de74a,2017-06-03 20:05:00,NaT
6,6f22cd44-bc63-4449-a9af-2651859da2f9,2017-03-18 23:09:00,NaT
7,49a6399b-c095-4e42-92eb-af90abe2bb6a,2017-01-10 12:09:00,NaT
8,653c095d-fd74-40dd-ae3b-5a69a2613629,2017-06-27 19:21:00,NaT
9,3d9fdac1-aae3-4a01-b448-934d12047468,2017-09-24 06:43:00,NaT

3. Find the number of tiemstamps that are **null** for the column **cart_time** and also **notnull** for the column **cart_time**.

In [44]:
cart_visits = pd.merge(visits, cart, how = 'left')

#Find the numbers of empty cart_time. 
cart_time = cart_visits[cart_visits.cart_time.isnull()]
cart_time2 = cart_visits[cart_visits.cart_time.notnull()]

In [194]:
#Count of the empty cart_time dataframe. 
cart_empty_count = cart_time.user_id.count()
cart_time_notnull = cart_time2.user_id.count()

print(f"Empty cart time count was {cart_empty_count}.")
print(f"Filled cart time count was {cart_time_notnull}.")

Empty cart time count was 1652.
Filled cart time count was 348.

4. Find the percantage of user who visited the Cool T-shirt ended up not placing the t-shirt in their cart.

In [199]:
percentage_empty_carts = cart_empty_count/(cart_count + cart_time_notnull) * 100
percentage_fill_carts = cart_time_notnull/(cart_count + cart_time_notnull) * 100
print(f"There are {percentage_empty_carts}% of empty carts for the data set.")
print(f"There are {percentage_fill_carts}% of filled carts for the data set.")

There are 82.6% of empty carts for the data set.
There are 17.4% of filled carts for the data set.

5. Perform a **left merge** for the **cart and checkout** dataframes and count empty values and merge the four data frames together into **all_data** frame.

In [205]:
pd.merge(cart, checkout, how = 'left')

,user_id,cart_time,checkout_time
0,2be90e7c-9cca-44e0-bcc5-124b945ff168,2017-11-07 20:45:00,2017-11-07 21:14:00
1,2be90e7c-9cca-44e0-bcc5-124b945ff168,2017-11-07 20:45:00,2017-11-07 20:50:00
2,2be90e7c-9cca-44e0-bcc5-124b945ff168,2017-11-07 20:45:00,2017-11-07 21:11:00
3,4397f73f-1da3-4ab3-91af-762792e25973,2017-05-27 01:35:00,NaT
4,a9db3d4b-0a0a-4398-a55a-ebb2c7adf663,2017-03-04 10:38:00,2017-03-04 11:04:00
...,...,...,...
477,59d2b685-383a-4fce-a325-35d985713a8b,2017-01-20 03:58:00,NaT
478,a1203970-92ae-4fc7-843e-e1740c1be9d5,2017-11-12 23:07:00,NaT
479,55de53ae-89f6-43ff-a26d-df284678aca1,2017-03-17 19:56:00,2017-03-17 20:04:00
480,0ea4cc68-dae4-4e35-b3e0-f0889932e1b5,2017-05-12 08:53:00,2017-05-12 08:57:00
481,0ea4cc68-dae4-4e35-b3e0-f0889932e1b5,2017-05-12 08:53:00,2017-05-12 09:20:00

In [206]:
all_data = visits.merge(cart, how = 'left').merge(checkout, how = 'left').merge(purchase, how = 'left')

6. Print the all_data frame for the first five rows.

In [207]:
print(all_data.head(5))

                                user_id          visit_time  \
0  943647ef-3682-4750-a2e1-918ba6f16188 2017-04-07 15:14:00
1  0c3a3dd0-fb64-4eac-bf84-ba069ce409f2 2017-01-26 14:24:00
2  6e0b2d60-4027-4d9a-babd-0e7d40859fb1 2017-08-20 08:23:00
3  6879527e-c5a6-4d14-b2da-50b85212b0ab 2017-11-04 18:15:00
4  a84327ff-5daa-4ba1-b789-d5b4caf81e96 2017-02-27 11:25:00

            cart_time       checkout_time       purchase_time
0                 NaT                 NaT                 NaT
1 2017-01-26 14:44:00 2017-01-26 14:54:00 2017-01-26 15:08:00
2 2017-08-20 08:31:00                 NaT                 NaT
3                 NaT                 NaT                 NaT
4                 NaT                 NaT                 NaT

## 5. Perform EDA on the All Data Frame ##

**Introduction:** In this section, I got through the aspect of the **all_data** dataframe.

1. Review the first five rows of the **all_data** dataframe.

In [210]:
print(all_data.head(5))

                                user_id          visit_time  \
0  943647ef-3682-4750-a2e1-918ba6f16188 2017-04-07 15:14:00
1  0c3a3dd0-fb64-4eac-bf84-ba069ce409f2 2017-01-26 14:24:00
2  6e0b2d60-4027-4d9a-babd-0e7d40859fb1 2017-08-20 08:23:00
3  6879527e-c5a6-4d14-b2da-50b85212b0ab 2017-11-04 18:15:00
4  a84327ff-5daa-4ba1-b789-d5b4caf81e96 2017-02-27 11:25:00

            cart_time       checkout_time       purchase_time
0                 NaT                 NaT                 NaT
1 2017-01-26 14:44:00 2017-01-26 14:54:00 2017-01-26 15:08:00
2 2017-08-20 08:31:00                 NaT                 NaT
3                 NaT                 NaT                 NaT
4                 NaT                 NaT                 NaT

2. Find the percentage of users proceeded to checkout but did not purchase a t-shirt.

In [224]:
count_checked_out = "{:.2f}".format((all_data[all_data.checkout_time.notnull() & all_data.purchase_time.isnull()].user_id.count())/all_data.user_id.count() * 100)
print(f"There are {count_checked_out}% of people that checked out their items but did not purchase a t-shirt.")

There are 4.26% of people that checked out their items but did not purchase a t-shirt.

## Summary ##

In this project, I go over the proper process of importing raw data from csv files into the Python Notebook to extract, stage, clean, and presented them in a meaningful text information.